<body>
    <header>
        <!-- Intro settings -->
        <style>
            #intro {
                /* Margin to fix overlapping fixed navbar */
                margin-top: 58px;
            }

            @media (max-width: 991px) {
                #intro {
                    /* Margin to fix overlapping fixed navbar */
                    margin-top: 45px;
                }
            }
        </style>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
            <div class="container-fluid">
                <!-- Navbar brand -->
                <span class="navbar-brand">
                    <b>Foodie</b>
                </span>
                <div class="collapse navbar-collapse" id="navbarExample01">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/manager">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/manager/food" rel="nofollow">Add Food</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav d-flex flex-row">
                        <!-- Button -->
                        <li class="nav-item me-3 me-lg-0">
                            <a class="nav-link" href="/">
                                <button class="bg-primary p-1">sign out</button>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Navbar -->

    </header>
    <!--Main Navigation-->

    <!--Main layout-->
    <main class="my-5">
        <div class="container">
            <!--Section: Content-->
            <section class="text-center">
                <h4 class="mb-5 p-4"><strong>Update Food List</strong></h4>
                <form action="/manager/update?id=<?php echo $data['_id'] ?>" method="post">
                    <p>
                        <label for="name">Name: </label>
                        <input class="form-control" type="text" name="name" value="<?php echo $data['name'] ?>">
                    </p>
                    <p>
                        <label for="rating">Rating: </label>
                        <input class="form-control" type="number" name="rating" value="<?php echo $data['rating'] ?>">
                    </p>
                    <p>
                        <label for="price">Price: </label>
                        <input class="form-control" type="number" name="price"  value="<?php echo $data['price'] ?>">
                    </p>
                    <p>
                        <label for="image">Image: </label>
                        <input class="form-control" type="text" name="image"  value="<?php echo $data['image'] ?>">
                    </p>
                    <p>
                        <label for="origin">Origin: </label>
                        <input class="form-control" type="text" name="origin"  value="<?php echo $data['origin'] ?>">
                    </p>
                    <button class="btn btn-success" type="submit">Update</button>
                </form>

            <!--Section: Content-->

        </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    <footer class="bg-light text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-dark" href="">Foodie.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!--Footer-->
</body>
